[package]
name = "rastreador"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.28", default-features = false, features = ["ptrace", "process", "signal"] }
libc = "0.2"
clap = { version = "4", features = ["derive"] }
termios = "0.3"
anyhow = "1"

